global:
  resolve_timeout: 1h
  smtp_from: prometheus@demo.com
  smtp_smarthost: demo.com:25
  smtp_require_tls: false
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  slack_api_url: https://hooks.slack.com/services/T12345/T12345/12345

#####################################################
templates:
- /etc/alertmanager/template/*.tmpl

#####################################################
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - cluster
  - service

#####################################################
route:
  receiver: 'default-email'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h
  routes:
  - receiver: 'infrastructure-monitoring-email'
    match_re:
      service: ^(infrastructure*)$

  - receiver: 'kubernetes-monitoring-email'
    match_re:
      service: kubernetes-monitoring-blackbox

  - receiver: 'test-service-team'
    match:
      service: test-service-blackbox
################ ALERT_ROUTES ABOVE #################
#####################################################
receivers:
- name: 'default-email'
  email_configs:
  - send_resolved: true
    to: demo@tomarv2.com
    from: prometheus@demo.com
    smarthost: demo.com:25
    headers:
      From: prometheus@demo.com
      Subject: '{{ template "email.default.subject" . }}'
      To: demo@tomarv2.com
    html: '{{ template "email.default.html" . }}'
    require_tls: false
#  slack_configs:
#  - send_resolved: true
#    api_url: https://hooks.slack.com/services/T12345/T12345/T12345
#    channel: devops-alerts
################### END JOB #########################

################# START JOB #########################
- name: 'demo-team'
  email_configs:
  - send_resolved: true
    to: 'demo@tomarv2.com' # DO NOT REMOVE TAG: demo-team
    from: prometheus@demo.com
    smarthost: demo.com:25
    headers:
      From: prometheus@demo.com
      Subject: '{{ template "email.default.subject" . }}'
      To: 'demo@tomarv2.com' # DO NOT REMOVE TAG: demo-team
    html: '{{ template "email.default.html" . }}'
    require_tls: false
  pagerduty_configs:
  - send_resolved: true
    service_key: 123456789 # DO NOT REMOVE TAG: demo-team
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{template "pagerduty.default.description" .}}'
  slack_configs:
  - send_resolved: true 
    api_url: https://hooks.slack.com/services/T12345/T12345/T12345
    channel:  "devops-alerts" # DO NOT REMOVE TAG: demo-team
################### END JOB #########################
################# START JOB #########################                                                        
- name: 'kubernetes-monitoring-email'
  email_configs:
  - send_resolved: true
    to: 'demo@tomarv2.com,demo1@demo.com' ## TO CHANGE!!!
    from: prometheus@demo.com
    smarthost: demo.com:25
    headers:
      From: prometheus@demo.com
      Subject: '{{ template "email.default.subject" . }}'
      To: 'demo@tomarv2.com,demo1@demo.com' ## TO CHANGE!!!
    html: '{{ template "email.default.html" . }}'
    require_tls: false
  slack_configs:
  - send_resolved: true
    api_url: https://hooks.slack.com/services/T12345/T12345/T12345
    channel: devops-alerts
    text: '{{ .GroupLabels.alertname }}: {{ .Annotations.summary }} {{ end }}'
################### END JOB #########################
################# START JOB #########################
- name: 'test-service-team'
  email_configs:
  - send_resolved: true
    to: 'demo@tomarv2.com' # DO NOT REMOVE TAG: test-service-team
    from: prometheus@demo.com
    smarthost: demo.com:25
    headers:
      From: prometheus@demo.com
      Subject: '{{ template "email.default.subject" . }}'
      To: 'demo@tomarv2.com' # DO NOT REMOVE TAG: test-service-team
    html: '{{ template "email.default.html" . }}'
    require_tls: false
  pagerduty_configs:
  - send_resolved: true
    service_key: 123456789 # DO NOT REMOVE TAG: test-service-team
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{template "pagerduty.default.description" .}}'
  slack_configs:
  - send_resolved: true
    api_url: https://hooks.slack.com/services/T12345/T12345/T12345
    channel: "devops-alerts"
  - send_resolved: true 
    api_url: https://hooks.slack.com/services/T12345/T12345/T12345
    channel:  "devops-alerts" # DO NOT REMOVE TAG: test-service-team
################### END JOB #########################
############## ALERT_RECEIVERS ABOVE ################
#####################################################
