

# Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-blackbox
  namespace: sharedservices
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: prometheus-blackbox.demo.com
    http:
      paths:
      - backend:
          serviceName: prometheus-blackbox
          servicePort: 9115
